# config/secrets.yml
development:
  # :devise_jwt_secret_key is left blank for development

test:
  # :devise_jwt_secret_key is left blank for testing

production:
  :devise_jwt_secret_key: <%= ENV['RAILS_JWT_SECRET_KEY'] %>
